name: Deployment workflow
on: 
  push:
  workflow_dispatch: 
    inputs:
      environment_type:
        description: "It contains in which environment we are running the test"
        required: false
        default: TEST

env:
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME}}
jobs:
  test:
    environment: ${{ github.event.inputs.environment_type }}
    env:
      MONGO_SERVER: ${{ secrets.MONGO_SERVER }}
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1
      - name: Setup Nodejs
        uses: actions/Setup-node@v4
        with:
          node-version: 18
      - name: Cache Dependencies
        uses: actions/Cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: print environment variables
        run: |
          echo "MONGO_DB_NAME: ${{ env.MONGO_DB_NAME}}"
          echo "MONGO_USER_NAME: ${{ env.MONGO_USER }}"
          echo "Environment is: ${{ github.event.inputs.environment_type }}"
          echo "environment: ${{ secrets.${{ github.event.inputs.environment_type }}_SECRET }}""
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4.1.1
      - name: Setup Nodejs
        uses: actions/Setup-node@v4
        with:
          node-version: 18
      - name: Cached Dependencies
        uses: actions/Cache@v4
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying.."
