name: Display value of github environmnet variable
on: 
  pull_request: 
    types: 
      - opened
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Access github environmnet variable
        run: echo "${{toJson(github)}}"
